force-app/env/objects/FeatureFlagSetting__mdt/FeatureFlagSetting__mdt.object-meta.xml
<CustomObject>
    <description
  >Setting for capturing a feature flag and how it should be processed.</description>
    <label>Feature Flag Setting</label>
    <pluralLabel>Feature Flag Settings</pluralLabel>
</CustomObject>

force-app/env/objects/FeatureFlagSetting__mdt/fields/RBACCategory__c.field-meta.xml
<CustomField>
    <fullName>RBACCategory__c</fullName>
    <description>Category of permissions used to determine whether or not a user has a feature active for them.</description>
    <inlineHelpText>Category of permissions used to determine whether or not a user has a feature active for them.</inlineHelpText>
    <label>RBAC Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profile</fullName>
                <default>true</default>
                <label>Profile</label>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Public Group</fullName>
            </value>
            <value>
                <fullName>Custom Permission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/env/objects/FeatureFlagSetting__mdt/fields/RBACCategoryValue__c.field-meta.xml
<CustomField>
    <fullName>RBACCategoryValue__c</fullName>
    <description>The value used to match if using RBAC Category and the RBACFeatureResolver. Can be a comma-delimited string of appropriate values. If values exceeds 255 characters, consider a different mechanism for giving access to a feature, such as using a single custom permission.</description>
    <inlineHelpText>The value used to match if using RBAC Category and the RBACFeatureResolver. Can be a comma-delimited string of appropriate values. If values exceeds 255 characters, consider a different mechanism for giving access to a feature, such as using a single custom permission.</inlineHelpText>
    <label>RBAC Category Value</label>
    <type>TextArea</type>
</CustomField>

force-app/env/classes/tests/RBACFeatureResolverTest.cls
@IsTest
@SuppressWarnings('PMD.MethodNamingConventions')
private inherited sharing class RBACFeatureResolverTest {
  @IsTest
  private static void resolve_profileIsFlagged_returnTrue() {
    String profileName = [
      SELECT Id, Name
      FROM Profile
      WHERE Id = :UserInfo.getProfileId()
      LIMIT 1
    ]
    .Name;
    String value = profileName + ',SomethingElse';
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Profile',
      RBACCategoryValue__c = value
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getProfiles' => new ReturnValueMethodMock(
            new List<Profile>{ new Profile(Name = profileName) }
          )
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      true,
      result,
      'Should return true since profile is captured'
    );
  }
  @IsTest
  private static void resolve_profileIsNotFlagged_returnFalse() {
    String profileName = [
      SELECT Id, Name
      FROM Profile
      WHERE Id = :UserInfo.getProfileId()
      LIMIT 1
    ]
    .Name;
    String value = 'SomethingElse';
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Profile',
      RBACCategoryValue__c = value
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getProfiles' => new ReturnValueMethodMock(
            new List<Profile>{ new Profile(Name = profileName) }
          )
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      false,
      result,
      'Should return false since profile is not captured'
    );
  }
  @IsTest
  private static void resolve_invalidProfile_returnFalse() {
    String value = 'SomethingElse';
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Profile',
      RBACCategoryValue__c = value
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getProfiles' => new ReturnValueMethodMock(new List<Profile>())
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      false,
      result,
      'Should return false since no profile returned'
    );
  }
  @IsTest
  private static void resolve_hasPermissionSet_returnTrue() {
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Permission Set',
      RBACCategoryValue__c = 'SomeValue'
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getPermissionSetAssignments' => new ReturnValueMethodMock(
            new List<PermissionSetAssignment>{ new PermissionSetAssignment() }
          )
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      true,
      result,
      'Should return true when permission set assignment is found'
    );
  }
  @IsTest
  private static void resolve_noPermissionSet_returnFalse() {
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Permission Set',
      RBACCategoryValue__c = 'SomeValue'
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getPermissionSetAssignments' => new ReturnValueMethodMock(
            new List<PermissionSetAssignment>()
          )
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      false,
      result,
      'Should return false when no permission set assignment is found'
    );
  }
  @IsTest
  private static void resolve_noCustomPermission_returnFalse() {
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Custom Permission',
      RBACCategoryValue__c = 'SomeValue'
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getCustomPermissionValue' => new ReturnValueMethodMock(false)
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      false,
      result,
      'Should return false when no custom permission is found'
    );
  }
  @IsTest
  private static void resolve_hasGroup_returnTrue() {
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Public Group',
      RBACCategoryValue__c = 'SomeValue'
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getGroupMembers' => new ReturnValueMethodMock(
            new List<GroupMember>{ new GroupMember() }
          )
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      true,
      result,
      'Should return true when group assignment is found'
    );
  }
  @IsTest
  private static void resolve_noGroup_returnFalse() {
    RBACFeatureResolver resolver = new RBACFeatureResolver();
    resolver.config = new FeatureFlagSetting__mdt(
      RBACCategory__c = 'Public Group',
      RBACCategoryValue__c = 'SomeValue'
    );
    resolver.selector = (FeatureFlagConfigSelector) System.Test.createStub(
      FeatureFlagConfigSelector.class,
      Testing.mocks.createClassMocker(
        new Map<String, IMethodMock>{
          'getGroupMembers' => new ReturnValueMethodMock(
            new List<GroupMember>()
          )
        }
      )
    );
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(
      false,
      result,
      'Should return false when no group assignment is found'
    );
  }
}