force-app/env/objects/FeatureFlagSetting__mdt/FeatureFlagSetting__mdt.object-meta.xml
<CustomObject>
    <description
  >Setting for capturing a feature flag and how it should be processed.</description>
    <label>Feature Flag Setting</label>
    <pluralLabel>Feature Flag Settings</pluralLabel>
</CustomObject>

force-app/env/objects/FeatureFlagSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description
  >The name of the feature flag resolver class that should be used.</description>
    <inlineHelpText
  >The name of the feature flag resolver class that should be used.</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/env/classes/FeatureFlagConfigSelector.cls
/**
 * @description Selector for retrieving configuration for feature flags
 * @date 2022-06-25
 * @group Env
 */
public inherited sharing class FeatureFlagConfigSelector {
  /**
   * @description returns a feature flag config record
   * @param featureDevName Developer name of the feature flag config record
   * @return Record if it exists, null otherwise
   */
  @SuppressWarnings('PMD.ApexCRUDViolation')
  public FeatureFlagSetting__mdt getFeatureConfig(String featureDevName) {
    List<FeatureFlagSetting__mdt> flag = [
      SELECT DeveloperName, ClassName__c
      FROM FeatureFlagSetting__mdt
      WHERE DeveloperName = :featureDevName
    ];
    return flag.isEmpty() ? null : flag[0];
  }
}