force-app/env/objects/FeatureFlagSetting__mdt/FeatureFlagSetting__mdt.object-meta.xml
<CustomObject>
    <description
  >Setting for capturing a feature flag and how it should be processed.</description>
    <label>Feature Flag Setting</label>
    <pluralLabel>Feature Flag Settings</pluralLabel>
</CustomObject>

force-app/env/objects/FeatureFlagSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not a Salesforce-driven feature is toggled on.</description>
    <inlineHelpText>Whether or not a Salesforce-driven feature is toggled on.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/env/classes/tests/SimpleFeatureResolverTest.cls
@IsTest
@SuppressWarnings('PMD.MethodNamingConventions')
private inherited sharing class SimpleFeatureResolverTest {
  @IsTest
  private static void resolve_isActive_returnTrue() {
    FeatureFlagSetting__mdt setting = new FeatureFlagSetting__mdt(
      IsActive__c = true
    );
    SimpleFeatureResolver resolver = new SimpleFeatureResolver();
    resolver.config = setting;
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(true, result, 'Should return true based on config');
  }

  @IsTest
  private static void resolve_isNotActive_returnFalse() {
    FeatureFlagSetting__mdt setting = new FeatureFlagSetting__mdt(
      IsActive__c = false
    );
    SimpleFeatureResolver resolver = new SimpleFeatureResolver();
    resolver.config = setting;
    System.Test.startTest();
    Boolean result = resolver.resolve();
    System.Test.stopTest();
    System.assertEquals(false, result, 'Should return false based on config');
  }
}