force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Trigger-level setting for managing trigger logic for an SObject</description>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not triggers are active for the SObject.</description>
    <inlineHelpText>Whether or not triggers are active for the SObject.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description
  >Priority of execution, with lower numbers being executed first. SObject Settings with no priority will be executed last. Useful for package-based development.</description>
    <inlineHelpText
  >Priority of execution, with lower numbers being executed first. SObject Settings with no priority will be executed last. Useful for package-based development.</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>The type of SObject (e.g. Account) that this setting is for.</description>
    <inlineHelpText>The type of SObject (e.g. Account) that this setting is for.</inlineHelpText>
    <label>SObject Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/TriggerHandlerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Handler-level setting for managing trigger logic for an SObject.</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the trigger handler class that this configuration injects.</description>
    <inlineHelpText>The name of the trigger handler class that this configuration injects.</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not the trigger handler is active.</description>
    <inlineHelpText>Whether or not the trigger handler is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority of execution, with lower numbers being executed first. Handlers with no priority will be executed last.</description>
    <inlineHelpText>Priority of execution, with lower numbers being executed first. Handlers with no priority will be executed last.</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/SObjectTriggerSetting__c.field-meta.xml
<CustomField>
    <fullName>SObjectTriggerSetting__c</fullName>
    <description>The SObject setting that this handler should be bound to.</description>
    <inlineHelpText>The SObject setting that this handler should be bound to.</inlineHelpText>
    <label>SObject Trigger Setting</label>
    <referenceTo>SObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>Trigger Handler Settings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/trigger-framework/classes/TriggerConfigSelector.cls
/**
 * @description Selector class for returning configuration related to trigger functionality
 * @author Tom Wilkins
 * @date 2022-04-12
 * @group Triggers
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public inherited sharing class TriggerConfigSelector {
  public List<SObjectTriggerSetting__mdt> getTriggerSettings(
    Schema.SObjectType sObjType
  ) {
    return [
      SELECT
        SObjectType__c,
        (
          SELECT ClassName__c
          FROM TriggerHandlerSettings__r
          WHERE IsActive__c = TRUE
          ORDER BY Priority__c ASC NULLS LAST
        )
      FROM SObjectTriggerSetting__mdt
      WHERE SObjectType__c = :String.valueOf(sObjType) AND IsActive__c = TRUE
    ];
  }
}