force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Trigger-level setting for managing trigger logic for an SObject</description>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/TriggerHandlerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Handler-level setting for managing trigger logic for an SObject.</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the trigger handler class that this configuration injects.</description>
    <inlineHelpText>The name of the trigger handler class that this configuration injects.</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/SObjectTriggerSetting__c.field-meta.xml
<CustomField>
    <fullName>SObjectTriggerSetting__c</fullName>
    <description>The SObject setting that this handler should be bound to.</description>
    <inlineHelpText>The SObject setting that this handler should be bound to.</inlineHelpText>
    <label>SObject Trigger Setting</label>
    <referenceTo>SObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>Trigger Handler Settings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/trigger-framework/classes/tests/TriggerDispatcherFactoryTest.cls
@IsTest
@SuppressWarnings('PMD.MethodNamingConventions')
private inherited sharing class TriggerDispatcherFactoryTest {
  @IsTest
  private static void create_mockedSelector_returnOneHandler() {
    SObjectMocker handlerSettingMocker = new SObjectMocker(
      TriggerHandlerSetting__mdt.getSObjectType(),
      TriggerHandlerSetting__mdt.class
    );
    SObjectMocker triggerSettingMocker = new SObjectMocker(
        SObjectTriggerSetting__mdt.getSObjectType(),
        SObjectTriggerSetting__mdt.class
      )
      .setRelatedList(
        'Libs__TriggerHandlerSettings__r',
        new List<TriggerHandlerSetting__mdt>{
          (TriggerHandlerSetting__mdt) handlerSettingMocker.generateMockSObject(
            new Map<Schema.SObjectField, Object>{
              TriggerHandlerSetting__mdt.ClassName__c => 'TriggerHandlerMock'
            }
          )
        }
      );
    SObjectTriggerSetting__mdt config = (SObjectTriggerSetting__mdt) triggerSettingMocker.generateMockSObject();
    TriggerDispatcherFactory factory = new TriggerDispatcherFactory();
    factory.config = (TriggerConfigSelector) Testing.mocks.mockClass(
      TriggerConfigSelector.class,
      new Map<String, IMethodMock>{
        'getTriggerSettings' => new ReturnValueMethodMock(
          new List<SObjectTriggerSetting__mdt>{ config }
        )
      }
    );
    System.Test.startTest();
    TriggerDispatcher dispatcher = factory.create(Account.getSObjectType());
    System.Test.stopTest();
    System.assertEquals(
      1,
      dispatcher.handlers.size(),
      'Should return the 1 configured handler'
    );
  }
}