force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Trigger-level setting for managing trigger logic for an SObject</description>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/TriggerHandlerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Handler-level setting for managing trigger logic for an SObject.</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the trigger handler class that this configuration injects.</description>
    <inlineHelpText>The name of the trigger handler class that this configuration injects.</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/trigger-framework/objects/TriggerHandlerSetting__mdt/fields/SObjectTriggerSetting__c.field-meta.xml
<CustomField>
    <fullName>SObjectTriggerSetting__c</fullName>
    <description>The SObject setting that this handler should be bound to.</description>
    <inlineHelpText>The SObject setting that this handler should be bound to.</inlineHelpText>
    <label>SObject Trigger Setting</label>
    <referenceTo>SObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>Trigger Handler Settings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/trigger-framework/classes/TriggerDispatcherFactory.cls
/**
 * @description Factory for creating trigger dispatcher and injecting handlers based on configuring
 * @author Tom Wilkins
 * @date 2022-04-13
 * @group Triggers
 */
@SuppressWarnings('PMD.AvoidGlobalModifier')
global inherited sharing class TriggerDispatcherFactory {
  @TestVisible
  private static Map<String, List<ITriggerHandler>> cachedHandlers {
    get {
      if (cachedHandlers == null) {
        cachedHandlers = new Map<String, List<ITriggerHandler>>();
      }
      return cachedHandlers;
    }
    set;
  }
  @TestVisible
  private TriggerConfigSelector config {
    get {
      if (this.config == null) {
        this.config = new TriggerConfigSelector();
      }
      return this.config;
    }
    set;
  }
  /**
   * @description Creates and returns a trigger dispatcher for the provided SObject
   * @param sObjType the type of SObject to create a dispatcher for
   * @return Trigger dispatcher with injected handlers for the provided SObject
   */
  global TriggerDispatcher create(Schema.SObjectType sObjType) {
    String sObjString = String.valueOf(sObjType);
    List<ITriggerHandler> handlers;
    // cache for potential recursive trigger invocations
    // this will be udpated in the future when cache managers are implemented
    if (cachedHandlers.containsKey(sObjString)) {
      handlers = cachedHandlers.get(sObjString);
    } else {
      for (
        SObjectTriggerSetting__mdt setting : this.config.getTriggerSettings(
          sObjType
        )
      ) {
        for (
          TriggerHandlerSetting__mdt handlerSetting : setting.TriggerHandlerSettings__r
        ) {
          handlers.add(
            (ITriggerHandler) Type.forName(handlerSetting.ClassName__c)
              .newInstance()
          );
        }
      }
      cachedHandlers.put(sObjString, handlers);
    }
    return new TriggerDispatcher(handlers);
  }
}